### ISSUE TITLE
500 internal server errors on test pilot dev

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1157]
Investigating - appears to be a broken DB migration. Blocks further deployment

**Comment by lmorchard** [comment]
Still investigating. Looks like one of the 500 errors is producing this in Python, which suggests the last migration adding the notification model changes didn't get applied:

```

-------------------------------------
/var/log/eb-docker/containers/eb-current-app/912c958c42fc-stdouterr.log
-------------------------------------
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 658, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 223, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 598, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 598, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.5/site-packages/hvad/contrib/restframework/serializers.py", line 183, in to_representation
    return super(TranslatableModelMixin, self).to_representation(instance)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 456, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 598, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "experiments_experimentnotification" does not exist
LINE 1: ...periments_experimentnotification"."modified" FROM "experimen...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.5/site-packages/mozilla_cloud_services_logger/formatters.py", line 85, in format
    return json.dumps(out)
  File "/usr/local/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <WSGIRequest: GET '/api/experiments'> is not JSON serializable
Call stack:
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 174, in run
    self.manage_workers()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 540, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 124, in init_process
    self.run()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 119, in run
    self.run_for_one(timeout)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 66, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 30, in accept
    self.handle(listener, client, addr)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.5/site-packages/whitenoise/base.py", line 119, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 256, in handle_uncaught_exception
    'request': request
Message: 'Internal Server Error: %s'
Arguments: ('/api/experiments',)
{"Severity": 6, "EnvVersion": "2.0", "Type": "request.summary", "Fields": {"t": 65, "rid": "ea4abf9a-55d1-11e6-9740-0242ac110002", "uid": "", "errno": 0, "method": "GET", "agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:50.0) Gecko/20100101 Firefox/50.0", "path": "/api/experiments", "lang": "en-US,en;q=0.5"}, "Pid": 20, "Hostname": "912c958c42fc", "Timestamp": 1469827074933070592, "Logger": "TestPilot"}
```

**Comment by ckprice** [comment]
See this error in console

`None of the "sha384" hashes in the integrity attribute match the content of the subresource`

It's a reach, but matches the summary in #950.

**Comment by lmorchard** [comment]
No, I don't think SRI errors are related to this.

Just attempted manual migration on the elastic beanstalk container and got this:

```
~ $ ./manage.py migrate experiments
Operations to perform:
  Apply all migrations: experiments
Running migrations:
  Rendering model states... DONE
  Applying experiments.0019_auto_20160707_2050...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: could not create unique index "experiments_userinstallatio_experiment_id_15c759788ac8b5e1_uniq"
DETAIL:  Key (experiment_id, client_id)=(3, b2bbc36e-703b-e14d-9eb3-841b5e1cef62) is duplicated.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 324, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: could not create unique index "experiments_userinstallatio_experiment_id_15c759788ac8b5e1_uniq"
DETAIL:  Key (experiment_id, client_id)=(3, b2bbc36e-703b-e14d-9eb3-841b5e1cef62) is duplicated.
```

**Comment by ckprice** [comment]
Delete the dev data and try?

**Comment by lmorchard** [comment]
> Delete the dev data and try?

No. Whatever is wrong with migrations on dev is likely to happen to stage & prod if we go forward, and we're not going to delete data there.

**Comment by pdehaan** [comment]
Is this something Sentry would help catch? #684 
Or is this failing before Sentry would have a chance to catch+log it?

**Comment by lmorchard** [comment]
More infodump... this is the state of migrations on dev, for some reason it thinks 0019 in experiments from 3 weeks ago is unapplied, and it's trying to re-apply:

```
~ $ ./manage.py showmigrations
admin
 [X] 0001_initial
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
database
 [X] 0001_initial
experiments
 [X] 0001_initial
 [X] 0002_auto_20150831_1658
 [X] 0003_auto_20151021_2102
 [X] 0004_experiment_addon_id
 [X] 0005_auto_20151111_1758
 [X] 0006_auto_20151119_1849
 [X] 0007_experiment_privacy_notice_url
 [X] 0008_auto_20160111_1702
 [X] 0009_experiment_short_title
 [X] 0010_auto_20160202_2211
 [X] 0011_feature_featurecondition_featurestate
 [X] 0012_auto_20160317_1352
 [X] 0013_auto_20160329_1941
 [X] 0014_remove_userfeedback
 [X] 0015_experimenttourstep
 [X] 0016_auto_20160512_1704
 [X] 0017_discourse_url
 [X] 0018_auto_20160709_0247
 [ ] 0019_auto_20160707_2050
 [ ] 0020_auto_20160727_1846
 [ ] 0021_auto_20160729_1522
product_details
 [X] 0001_initial
 [X] 0002_auto_20151006_1348
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
users
 [X] 0001_initial
 [X] 0002_userprofile_invite_pending
waffle
 [X] 0001_initial
```

**Comment by lmorchard** [comment]
> Is this something Sentry would help catch? #684
> Or is this failing before Sentry would have a chance to catch+log it?

Sentry would catch the server errors, but this is a deployment issue

**Comment by lmorchard** [comment]
Managed to get dev working again by skipping the migration and running the rest:

```
~ $ ./manage.py migrate --fake experiments 0019_auto_20160707_2050
Operations to perform:
  Target specific migration: 0019_auto_20160707_2050, from experiments
Running migrations:
  Rendering model states... DONE
  Applying experiments.0019_auto_20160707_2050... FAKED
~ $ ./manage.py migrate experiments
Operations to perform:
  Apply all migrations: experiments
Running migrations:
  Rendering model states... DONE
  Applying experiments.0020_auto_20160727_1846... OK
  Applying experiments.0021_auto_20160729_1522... OK
```

**Comment by lmorchard** [comment]
And now `showmigrations` looks like this, but I still don't know why that migration from 7/7/2016 wasn't run on dev. Maybe it broke back then and has not been running this whole time but didn't cause other issues?

```
~ $ ./manage.py showmigrations
admin
 [X] 0001_initial
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
database
 [X] 0001_initial
experiments
 [X] 0001_initial
 [X] 0002_auto_20150831_1658
 [X] 0003_auto_20151021_2102
 [X] 0004_experiment_addon_id
 [X] 0005_auto_20151111_1758
 [X] 0006_auto_20151119_1849
 [X] 0007_experiment_privacy_notice_url
 [X] 0008_auto_20160111_1702
 [X] 0009_experiment_short_title
 [X] 0010_auto_20160202_2211
 [X] 0011_feature_featurecondition_featurestate
 [X] 0012_auto_20160317_1352
 [X] 0013_auto_20160329_1941
 [X] 0014_remove_userfeedback
 [X] 0015_experimenttourstep
 [X] 0016_auto_20160512_1704
 [X] 0017_discourse_url
 [X] 0018_auto_20160709_0247
 [X] 0019_auto_20160707_2050
 [X] 0020_auto_20160727_1846
 [X] 0021_auto_20160729_1522
product_details
 [X] 0001_initial
 [X] 0002_auto_20151006_1348
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
users
 [X] 0001_initial
 [X] 0002_userprofile_invite_pending
waffle
 [X] 0001_initial
```

**Comment by lmorchard** [comment]
Plot thickens a little bit - even though I skipped migration `0019`, we still needed it to do its thing. But I seem to have hit a Django bug with unique constraint changes. So, it needs to be done by hand or else our install counts will break. This is what I did on dev via postgresql-client:

```
ebdb=> alter table experiments_userinstallation drop constraint experiments_userinstal_user_id_1d954f0f8a5e7459_fk_auth_user_id;
ALTER TABLE
ebdb=> alter table experiments_userinstallation drop column user_id;
```

This needs doing on stage & prod - and might in fact be the cause of #1156. The catch is that the name of the constraint `experiments_userinstal_user_id_1d954f0f8a5e7459_fk_auth_user_id` will have a slightly different unique name (i.e. the hex string) on stage & prod respectively.

**Comment by lmorchard** [comment]
And now I'm just baffled. relud gave me access to stage, and I ran `showmigrations` on the container there. Apparently the failing migration _did_ apply there:

```
/app # ./manage.py showmigrations
admin
 [X] 0001_initial
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
database
 [X] 0001_initial
experiments
 [X] 0001_initial
 [X] 0002_auto_20150831_1658
 [X] 0003_auto_20151021_2102
 [X] 0004_experiment_addon_id
 [X] 0005_auto_20151111_1758
 [X] 0006_auto_20151119_1849
 [X] 0007_experiment_privacy_notice_url
 [X] 0008_auto_20160111_1702
 [X] 0009_experiment_short_title
 [X] 0010_auto_20160202_2211
 [X] 0011_feature_featurecondition_featurestate
 [X] 0012_auto_20160317_1352
 [X] 0013_auto_20160329_1941
 [X] 0014_remove_userfeedback
 [X] 0015_experimenttourstep
 [X] 0016_auto_20160512_1704
 [X] 0017_discourse_url
 [X] 0018_auto_20160709_0247
 [X] 0019_auto_20160707_2050
product_details
 [X] 0001_initial
 [X] 0002_auto_20151006_1348
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
users
 [X] 0001_initial
 [X] 0002_userprofile_invite_pending
waffle
 [X] 0001_initial
```

**Comment by lmorchard** [comment]
Going to mark this closed, but I'm eyeing it warily.

The problem happened on dev, but not stage - but it _did_ happen on prod. Manual SQL changes fixed prod.
