### ISSUE TITLE
Trying to generate a production quality stylesheet implodes and throws errors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#362]
### Steps to reproduce:
1. Clone the **idea-town** repo.
2. Change the `IS_DEBUG` const on line 27 of the gulpfile.js to `false`.
3. Run `$ gulp styles` from The Terminal.
### Actual results:

``` sh
$ gulp styles
[15:37:40] Using gulpfile ~/dev/tmp/del/idea-town/gulpfile.js
[15:37:40] Starting 'styles'...
/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map-consumer.js:703
        throw new Error('"' + aSource + '" is not in the SourceMap.');
        ^

Error: "node_modules/node-normalize-scss/_normalize.scss" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map-consumer.js:703:15)
    at SourceMapGenerator.<anonymous> (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map-generator.js:229:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map-generator.js:228:34)
    at applySourceMap (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/index.js:27:15)
    at /Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/index.js:56:13
    at whenSourceMapReady (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:139:16)
    at /Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:151:18
    at fromString (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/utils/input-source-map-tracker.js:33:10)
    at InputSourceMapStore.track (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/utils/input-source-map-tracker.js:236:5)
    at Object.whenDone (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:145:44)
    at processNext (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:105:13)
    at importFrom (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at ImportInliner.process (/Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:38:10)
    at /Users/pdehaan/dev/tmp/del/idea-town/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:120:41
    at doNTCallback0 (node.js:419:9)
```

**Comment by pdehaan** [comment]
For reference, here's the behavior with `IS_DEBUG = true` (default/current behavior):

**gulpfile.js:27**

``` js
const IS_DEBUG = true;
```

**OUTPUT:**

``` sh
$ gulp styles
[15:36:18] Using gulpfile ~/dev/tmp/del/idea-town/gulpfile.js
[15:36:18] Starting 'styles'...
[15:36:18] Finished 'styles' after 640 ms
```
